### ISSUE TITLE
How to use the models

### ISSUE THREAD

**Issue by serhangul** [Deep-Learning-Person-Re-Identification/Implementaion-1#14]
Hi, thanks for the code. This is sort of an absolute beginner question but how do you use the models to test the performance over the datasets once you compile the models. I ran `model_for_cuhk03.py` and got the message:
```
model definition complete
model definition done.
model compile done.
```
together with the network architecture. How do I continue from here?

**Comment by Ning-Ding** [comment]
@serhannn Hi, this is a project which I did four months ago. So I cannot remember everything that I did that time. For your question, you could look through the "train" function in the `model_for_cuhk03.py`, which is just in front of the "if __name__ == '__main__': ". You should open a ipython and use a command "run model_for_cuhk03.py" to compile the model, and then, try the command "train(model)". For more details, you could just read the code of function "train".

**Comment by serhangul** [comment]
@Ning-Ding Thanks, I could get it working now.
