### ISSUE TITLE
TypeError : get_updates() takes exactly 4 arguments (3 given)

### ISSUE THREAD

**Issue by MitraSafarinejad** [Deep-Learning-Person-Re-Identification/Implementaion-1#41]
Hi guys, I've installed all dependencies for this project, but when I run main.py I got this error:
TypeError:get_updates() takes exactly 4 arguments (3 given)

I've checked all files of project, my project has compiled successfully and couldn't find where this get_update used.
please help, I am in a hurry.

regards.
![screenshot from 2018-05-17 09-09-19](https://user-images.githubusercontent.com/39375115/40179396-3527fb8e-59b2-11e8-8d26-39031acee1dd.png)

**Comment by prashanthbasani** [comment]
Do you still need help? Please mention your Keras version.

**Comment by bmiftah** [comment]
hi , the function get_update()  is used in the model.py module ( one of the four module that makes up the whole project) - you find it inside the class SGD_new , the second function ... it takes four argument , one of them being self reference
  def get_updates(self, params, constraints, loss):
